import type * as Monaco from "monaco-editor";

/**
 * Python code snippets
 */
export const pythonSnippets = [
  {
    label: 'for',
    kind: 'Snippet' as const,
    insertText: 'for ${1:item} in ${2:iterable}:\n    ${0}',
    insertTextRules: 4, // InsertTextRule.InsertAsSnippet
    documentation: 'For loop',
    detail: 'for loop snippet',
  },
  {
    label: 'while',
    kind: 'Snippet' as const,
    insertText: 'while ${1:condition}:\n    ${0}',
    insertTextRules: 4,
    documentation: 'While loop',
    detail: 'while loop snippet',
  },
  {
    label: 'if',
    kind: 'Snippet' as const,
    insertText: 'if ${1:condition}:\n    ${0}',
    insertTextRules: 4,
    documentation: 'If statement',
    detail: 'if statement snippet',
  },
  {
    label: 'elif',
    kind: 'Snippet' as const,
    insertText: 'elif ${1:condition}:\n    ${0}',
    insertTextRules: 4,
    documentation: 'Elif statement',
    detail: 'elif statement snippet',
  },
  {
    label: 'else',
    kind: 'Snippet' as const,
    insertText: 'else:\n    ${0}',
    insertTextRules: 4,
    documentation: 'Else statement',
    detail: 'else statement snippet',
  },
  {
    label: 'def',
    kind: 'Snippet' as const,
    insertText: 'def ${1:function_name}(${2:parameters}):\n    ${0}',
    insertTextRules: 4,
    documentation: 'Function definition',
    detail: 'function definition snippet',
  },
  {
    label: 'class',
    kind: 'Snippet' as const,
    insertText: 'class ${1:ClassName}:\n    def __init__(self${2:, parameters}):\n        ${0}',
    insertTextRules: 4,
    documentation: 'Class definition',
    detail: 'class definition snippet',
  },
  {
    label: 'try',
    kind: 'Snippet' as const,
    insertText: 'try:\n    ${1}\nexcept ${2:Exception} as ${3:e}:\n    ${0}',
    insertTextRules: 4,
    documentation: 'Try-except block',
    detail: 'try-except snippet',
  },
  {
    label: 'with',
    kind: 'Snippet' as const,
    insertText: 'with ${1:expression} as ${2:variable}:\n    ${0}',
    insertTextRules: 4,
    documentation: 'With statement',
    detail: 'with statement snippet',
  },
  {
    label: 'lambda',
    kind: 'Snippet' as const,
    insertText: 'lambda ${1:parameters}: ${0}',
    insertTextRules: 4,
    documentation: 'Lambda function',
    detail: 'lambda snippet',
  },
  {
    label: 'ifmain',
    kind: 'Snippet' as const,
    insertText: 'if __name__ == "__main__":\n    ${0}',
    insertTextRules: 4,
    documentation: 'Main guard',
    detail: 'if main snippet',
  },
  {
    label: 'list',
    kind: 'Snippet' as const,
    insertText: '[${1:item} for ${2:item} in ${3:iterable}]',
    insertTextRules: 4,
    documentation: 'List comprehension',
    detail: 'list comprehension snippet',
  },
  {
    label: 'dict',
    kind: 'Snippet' as const,
    insertText: '{${1:key}: ${2:value} for ${3:item} in ${4:iterable}}',
    insertTextRules: 4,
    documentation: 'Dict comprehension',
    detail: 'dict comprehension snippet',
  },
];

/**
 * Java code snippets
 */
export const javaSnippets = [
  {
    label: 'main',
    kind: 'Snippet' as const,
    insertText: 'public static void main(String[] args) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Main method',
    detail: 'main method snippet',
  },
  {
    label: 'class',
    kind: 'Snippet' as const,
    insertText: 'public class ${1:ClassName} {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Class definition',
    detail: 'class snippet',
  },
  {
    label: 'for',
    kind: 'Snippet' as const,
    insertText: 'for (${1:int i = 0}; ${2:i < length}; ${3:i++}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'For loop',
    detail: 'for loop snippet',
  },
  {
    label: 'foreach',
    kind: 'Snippet' as const,
    insertText: 'for (${1:Type} ${2:item} : ${3:collection}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Enhanced for loop',
    detail: 'foreach snippet',
  },
  {
    label: 'while',
    kind: 'Snippet' as const,
    insertText: 'while (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'While loop',
    detail: 'while loop snippet',
  },
  {
    label: 'if',
    kind: 'Snippet' as const,
    insertText: 'if (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'If statement',
    detail: 'if statement snippet',
  },
  {
    label: 'else',
    kind: 'Snippet' as const,
    insertText: 'else {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Else statement',
    detail: 'else statement snippet',
  },
  {
    label: 'elseif',
    kind: 'Snippet' as const,
    insertText: 'else if (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Else if statement',
    detail: 'else if snippet',
  },
  {
    label: 'try',
    kind: 'Snippet' as const,
    insertText: 'try {\n    ${1}\n} catch (${2:Exception} ${3:e}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Try-catch block',
    detail: 'try-catch snippet',
  },
  {
    label: 'sys',
    kind: 'Snippet' as const,
    insertText: 'System.out.println(${0});',
    insertTextRules: 4,
    documentation: 'Print to console',
    detail: 'System.out.println snippet',
  },
  {
    label: 'sout',
    kind: 'Snippet' as const,
    insertText: 'System.out.println(${0});',
    insertTextRules: 4,
    documentation: 'Print to console',
    detail: 'System.out.println snippet',
  },
  {
    label: 'method',
    kind: 'Snippet' as const,
    insertText: 'public ${1:void} ${2:methodName}(${3:parameters}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Method definition',
    detail: 'method snippet',
  },
  {
    label: 'constructor',
    kind: 'Snippet' as const,
    insertText: 'public ${1:ClassName}(${2:parameters}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Constructor',
    detail: 'constructor snippet',
  },
  {
    label: 'switch',
    kind: 'Snippet' as const,
    insertText: 'switch (${1:expression}) {\n    case ${2:value}:\n        ${3}\n        break;\n    default:\n        ${0}\n}',
    insertTextRules: 4,
    documentation: 'Switch statement',
    detail: 'switch snippet',
  },
];

/**
 * C code snippets
 */
export const cSnippets = [
  {
    label: 'main',
    kind: 'Snippet' as const,
    insertText: 'int main() {\n    ${0}\n    return 0;\n}',
    insertTextRules: 4,
    documentation: 'Main function',
    detail: 'main function snippet',
  },
  {
    label: 'mainargs',
    kind: 'Snippet' as const,
    insertText: 'int main(int argc, char *argv[]) {\n    ${0}\n    return 0;\n}',
    insertTextRules: 4,
    documentation: 'Main function with arguments',
    detail: 'main with args snippet',
  },
  {
    label: 'for',
    kind: 'Snippet' as const,
    insertText: 'for (${1:int i = 0}; ${2:i < n}; ${3:i++}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'For loop',
    detail: 'for loop snippet',
  },
  {
    label: 'while',
    kind: 'Snippet' as const,
    insertText: 'while (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'While loop',
    detail: 'while loop snippet',
  },
  {
    label: 'if',
    kind: 'Snippet' as const,
    insertText: 'if (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'If statement',
    detail: 'if statement snippet',
  },
  {
    label: 'else',
    kind: 'Snippet' as const,
    insertText: 'else {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Else statement',
    detail: 'else statement snippet',
  },
  {
    label: 'elseif',
    kind: 'Snippet' as const,
    insertText: 'else if (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Else if statement',
    detail: 'else if snippet',
  },
  {
    label: 'function',
    kind: 'Snippet' as const,
    insertText: '${1:void} ${2:functionName}(${3:parameters}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Function definition',
    detail: 'function snippet',
  },
  {
    label: 'struct',
    kind: 'Snippet' as const,
    insertText: 'struct ${1:StructName} {\n    ${0}\n};',
    insertTextRules: 4,
    documentation: 'Struct definition',
    detail: 'struct snippet',
  },
  {
    label: 'switch',
    kind: 'Snippet' as const,
    insertText: 'switch (${1:expression}) {\n    case ${2:value}:\n        ${3}\n        break;\n    default:\n        ${0}\n}',
    insertTextRules: 4,
    documentation: 'Switch statement',
    detail: 'switch snippet',
  },
  {
    label: 'printf',
    kind: 'Snippet' as const,
    insertText: 'printf("${1:%s}\\n"${2:, variable});',
    insertTextRules: 4,
    documentation: 'Printf statement',
    detail: 'printf snippet',
  },
  {
    label: 'scanf',
    kind: 'Snippet' as const,
    insertText: 'scanf("${1:%d}", &${2:variable});',
    insertTextRules: 4,
    documentation: 'Scanf statement',
    detail: 'scanf snippet',
  },
];

/**
 * C++ code snippets
 */
export const cppSnippets = [
  {
    label: 'main',
    kind: 'Snippet' as const,
    insertText: 'int main() {\n    ${0}\n    return 0;\n}',
    insertTextRules: 4,
    documentation: 'Main function',
    detail: 'main function snippet',
  },
  {
    label: 'class',
    kind: 'Snippet' as const,
    insertText: 'class ${1:ClassName} {\npublic:\n    ${1:ClassName}();\n    ~${1:ClassName}();\nprivate:\n    ${0}\n};',
    insertTextRules: 4,
    documentation: 'Class definition',
    detail: 'class snippet',
  },
  {
    label: 'for',
    kind: 'Snippet' as const,
    insertText: 'for (${1:int i = 0}; ${2:i < n}; ${3:i++}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'For loop',
    detail: 'for loop snippet',
  },
  {
    label: 'foreach',
    kind: 'Snippet' as const,
    insertText: 'for (${1:auto}${2:&} ${3:item} : ${4:container}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Range-based for loop',
    detail: 'foreach snippet',
  },
  {
    label: 'while',
    kind: 'Snippet' as const,
    insertText: 'while (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'While loop',
    detail: 'while loop snippet',
  },
  {
    label: 'if',
    kind: 'Snippet' as const,
    insertText: 'if (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'If statement',
    detail: 'if statement snippet',
  },
  {
    label: 'else',
    kind: 'Snippet' as const,
    insertText: 'else {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Else statement',
    detail: 'else statement snippet',
  },
  {
    label: 'elseif',
    kind: 'Snippet' as const,
    insertText: 'else if (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Else if statement',
    detail: 'else if snippet',
  },
  {
    label: 'try',
    kind: 'Snippet' as const,
    insertText: 'try {\n    ${1}\n} catch (${2:std::exception}& ${3:e}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Try-catch block',
    detail: 'try-catch snippet',
  },
  {
    label: 'function',
    kind: 'Snippet' as const,
    insertText: '${1:void} ${2:functionName}(${3:parameters}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Function definition',
    detail: 'function snippet',
  },
  {
    label: 'cout',
    kind: 'Snippet' as const,
    insertText: 'std::cout << ${1} << std::endl;',
    insertTextRules: 4,
    documentation: 'Console output',
    detail: 'cout snippet',
  },
  {
    label: 'cin',
    kind: 'Snippet' as const,
    insertText: 'std::cin >> ${0};',
    insertTextRules: 4,
    documentation: 'Console input',
    detail: 'cin snippet',
  },
  {
    label: 'vector',
    kind: 'Snippet' as const,
    insertText: 'std::vector<${1:int}> ${2:name};',
    insertTextRules: 4,
    documentation: 'Vector declaration',
    detail: 'vector snippet',
  },
  {
    label: 'namespace',
    kind: 'Snippet' as const,
    insertText: 'namespace ${1:name} {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Namespace definition',
    detail: 'namespace snippet',
  },
];

/**
 * JavaScript code snippets
 */
export const jsSnippets = [
  {
    label: 'function',
    kind: 'Snippet' as const,
    insertText: 'function ${1:functionName}(${2:parameters}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Function declaration',
    detail: 'function snippet',
  },
  {
    label: 'arrow',
    kind: 'Snippet' as const,
    insertText: '(${1:parameters}) => {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Arrow function',
    detail: 'arrow function snippet',
  },
  {
    label: 'arrowshort',
    kind: 'Snippet' as const,
    insertText: '(${1:parameters}) => ${0}',
    insertTextRules: 4,
    documentation: 'Short arrow function',
    detail: 'short arrow function snippet',
  },
  {
    label: 'async',
    kind: 'Snippet' as const,
    insertText: 'async function ${1:functionName}(${2:parameters}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Async function',
    detail: 'async function snippet',
  },
  {
    label: 'asyncarrow',
    kind: 'Snippet' as const,
    insertText: 'async (${1:parameters}) => {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Async arrow function',
    detail: 'async arrow snippet',
  },
  {
    label: 'for',
    kind: 'Snippet' as const,
    insertText: 'for (let ${1:i} = 0; ${1:i} < ${2:array}.length; ${1:i}++) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'For loop',
    detail: 'for loop snippet',
  },
  {
    label: 'forof',
    kind: 'Snippet' as const,
    insertText: 'for (const ${1:item} of ${2:array}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'For-of loop',
    detail: 'for-of snippet',
  },
  {
    label: 'forin',
    kind: 'Snippet' as const,
    insertText: 'for (const ${1:key} in ${2:object}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'For-in loop',
    detail: 'for-in snippet',
  },
  {
    label: 'while',
    kind: 'Snippet' as const,
    insertText: 'while (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'While loop',
    detail: 'while loop snippet',
  },
  {
    label: 'if',
    kind: 'Snippet' as const,
    insertText: 'if (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'If statement',
    detail: 'if statement snippet',
  },
  {
    label: 'else',
    kind: 'Snippet' as const,
    insertText: 'else {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Else statement',
    detail: 'else statement snippet',
  },
  {
    label: 'elseif',
    kind: 'Snippet' as const,
    insertText: 'else if (${1:condition}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Else if statement',
    detail: 'else if snippet',
  },
  {
    label: 'try',
    kind: 'Snippet' as const,
    insertText: 'try {\n    ${1}\n} catch (${2:error}) {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Try-catch block',
    detail: 'try-catch snippet',
  },
  {
    label: 'trycatch',
    kind: 'Snippet' as const,
    insertText: 'try {\n    ${1}\n} catch (${2:error}) {\n    ${3}\n} finally {\n    ${0}\n}',
    insertTextRules: 4,
    documentation: 'Try-catch-finally block',
    detail: 'try-catch-finally snippet',
  },
  {
    label: 'class',
    kind: 'Snippet' as const,
    insertText: 'class ${1:ClassName} {\n    constructor(${2:parameters}) {\n        ${0}\n    }\n}',
    insertTextRules: 4,
    documentation: 'Class definition',
    detail: 'class snippet',
  },
  {
    label: 'switch',
    kind: 'Snippet' as const,
    insertText: 'switch (${1:expression}) {\n    case ${2:value}:\n        ${3}\n        break;\n    default:\n        ${0}\n}',
    insertTextRules: 4,
    documentation: 'Switch statement',
    detail: 'switch snippet',
  },
  {
    label: 'clg',
    kind: 'Snippet' as const,
    insertText: 'console.log(${0});',
    insertTextRules: 4,
    documentation: 'Console log',
    detail: 'console.log snippet',
  },
  {
    label: 'log',
    kind: 'Snippet' as const,
    insertText: 'console.log(${0});',
    insertTextRules: 4,
    documentation: 'Console log',
    detail: 'console.log snippet',
  },
  {
    label: 'promise',
    kind: 'Snippet' as const,
    insertText: 'new Promise((resolve, reject) => {\n    ${0}\n})',
    insertTextRules: 4,
    documentation: 'Promise',
    detail: 'promise snippet',
  },
  {
    label: 'timeout',
    kind: 'Snippet' as const,
    insertText: 'setTimeout(() => {\n    ${0}\n}, ${1:1000});',
    insertTextRules: 4,
    documentation: 'Set timeout',
    detail: 'setTimeout snippet',
  },
];

/**
 * Convert snippet to Monaco completion item format
 */
export const createSnippetCompletionItem = (
  snippet: typeof pythonSnippets[0],
  monaco: typeof Monaco,
  range: Monaco.IRange
): Monaco.languages.CompletionItem => {
  return {
    label: snippet.label,
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: snippet.insertText,
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: snippet.documentation,
    detail: snippet.detail,
    range: range,
  };
};
